version: '2'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    container_name: watchdog-zookeper
    

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    container_name: watchdog-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
